version: "3"
services:
  cache_server1:
    build: .
    ports:
      - 9527:9527
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      server:
          ipv4_address: 172.24.0.2
    command: ["python3", "cache_server.py", "9527", "172.24.0.2:50000", "172.24.0.3:50000", "172.24.0.4:50000"]

  cache_server2:
    build: .
    ports:
      - 9528:9528
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      server:
          ipv4_address: 172.24.0.3
    command: ["python3", "cache_server.py", "9528", "172.24.0.3:50000", "172.24.0.2:50000", "172.24.0.4:50000"]
 
  cache_server3:
    build: .
    ports:
      - 9529:9529
    networks:
      server:
          ipv4_address: 172.24.0.4
    deploy:
      restart_policy:
        condition: on-failure
    command: ["python3", "cache_server.py", "9529", "172.24.0.4:50000", "172.24.0.2:50000", "172.24.0.3:50000"]

networks:
  server:
    driver:
      bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
          gateway: 172.24.0.1